version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルド
          command: docker-compose build
      - run:
          name: bundle install
          command: docker-compose run backend bundle install
      - run:
          name: db:create and migrate
          command: |
            docker-compose run backend bundle exec rails db:create RAILS_ENV=test
            docker-compose run backend bundle exec rails db:migrate RAILS_ENV=test
      - run:
          name: webpacker
          command: |
            docker-compose run backend yarn install --check-files
            docker-compose run backend sh -c "yes | bundle exec rails webpacker:install"
            docker-compose run backend sh -c "yes | bundle exec rails webpacker:install:vue"
      - run:
          name: Run rspec
          command: docker-compose run backend bundle exec rspec
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down